### ISSUE TITLE
带哥CFHD出了个拆包宝箱活动

### ISSUE THREAD

**Issue by Sleepwa1ker** [qianjiachun/douyuEx#44]
逻辑和开宝箱不太一样麻烦加一下这些爬取功能...

**Comment by qianjiachun** [comment]
看了一下 没有能够自动完成的任务



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月19日(周四) 晚上11:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 带哥CFHD出了个拆包宝箱活动 (#44)




 
逻辑和开宝箱不太一样麻烦加一下这些爬取功能...
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
