### ISSUE TITLE
太牛了，碰到歆崽了

### ISSUE THREAD

**Issue by GlucoseHuang** [qianjiachun/douyuEx#45]
本来想找个斗鱼加密API的破解方法，居然搜到了歆崽做的插件

**Comment by qianjiachun** [comment]
啊这



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月23日(周一) 晚上6:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 太牛了，碰到歆崽了 (#45)




 
本来想找个斗鱼加密API的破解方法，居然搜到了歆崽做的插件
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GlucoseHuang** [comment]
5189167牛逼
