### ISSUE TITLE
作者有想过写api文件方便diy吗

### ISSUE THREAD

**Issue by xxaskong** [qianjiachun/douyuEx#46]
方便个人diy到每日自动执行

**Comment by qianjiachun** [comment]
目前没有这样的想法呃




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 上午9:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 作者有想过写api文件方便diy吗 (#46)





 
方便个人diy到每日自动执行
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
