### ISSUE TITLE
请问方便加一个防挂机检测的功能吗？

### ISSUE THREAD

**Issue by oneole** [qianjiachun/douyuEx#47]
有的时候直播间挂机太久斗鱼就问还在电脑前吗。。不知可否加一个防止挂机检测的功能 感激不尽！

**Comment by qianjiachun** [comment]
这个。。。不是很好弄 有机会再弄吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月29日(周三) 晚上10:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 请问方便加一个防挂机检测的功能吗？ (#47)




 
有的时候直播间挂机太久斗鱼就问还在电脑前吗。。不知可否加一个防止挂机检测的功能 感激不尽！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
