### ISSUE TITLE
想要自动参与抽奖（*＾-＾*）

### ISSUE THREAD

**Issue by Allen-Caolin** [qianjiachun/douyuEx#49]
希望脚本可以自动判断是否符合参与抽奖条件，条件符合自动不间断发送弹幕，抽奖结束自动停止，弹幕发送间隔可配置

**Comment by qianjiachun** [comment]
薅羊毛行为，不考虑




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 凌晨0:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 想要自动参与抽奖（*＾-＾*） (Issue #49)





 
希望脚本可以自动判断是否符合参与抽奖条件，条件符合自动不间断发送弹幕，抽奖结束自动停止，弹幕发送间隔可配置
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
