### ISSUE TITLE
请问Title-followNum是什么?为什么和显示的数字不一样

### ISSUE THREAD

**Issue by heartFire9** [qianjiachun/douyuEx#50]
![Snipaste_2021-11-14_06-33-34](https://user-images.githubusercontent.com/37868129/141660966-00551c26-de12-408e-9bf8-a0fee67be179.png)

**Comment by qianjiachun** [comment]
这个我不知道，问斗鱼吧...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 上午6:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 请问Title-followNum是什么?为什么和显示的数字不一样 (Issue #50)





 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
